#!/bin/sh

start() {
	# Start daemons.
	echo -n "Starting rpcbind: "
	rpcbind
	echo "done"
}

stop() {
	# Stop daemons.
	echo -n "Stopping rpcbind: "
	killall -q rpc.mountd
	echo "done"
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	stop
	start
	;;
  *)
	echo "Usage: rpcbind {start|stop|reload}"
	exit 1
esac

exit 0
